### ISSUE TITLE
On Safari Books Online there is a missing chapter

### ISSUE THREAD

**Issue by invegat** [mrosata/packt-mastering-fp#1]
At https://www.safaribooksonline.com/library/view/learning-path-javascript/9781788471282/video1_8.html the 'A Better Way to Map and Filter' section is a duplicate of the previous 'Promoting Reusability with Higher-Order Functions" and has nothing about Map or Filter.

**Comment by invegat** [comment]
In the  'A Better Way to Map and Filter' section the code shown isn't testing the last element of the array, the fix is below.
function every(predicate, [item, ...list]) {
  if (list.length) {
    return predicate(item) ? every(predicate,list) : false;
  }
  else {
   // return true;
     return item !== undefined ? predicate(item) : true;
  }

}

function some(predicate,[item, ...list]) {
  if (list.length) {
    return predicate(item) ? true : predicate(list);
  }
  // return false;
  return item !== undefined ? predicate(item) : false;
}

**Comment by mrosata** [comment]
Nice catch! Thanks for taking the time to post the problem and solution. I'll get this updated in the course as soon as possible.

I'm not sure how long it will take to update the videos on every course will take, so it might be a good idea to start an errata list in this repo as well. I'll credit you with this fix
 :smile:

**Comment by mrosata** [comment]
@invegat - The misplaced video was found and sent out yesterday, so that change should go through quickly. If not, I could make an inquiry to whether it's possible to give access to the missing content to those who need it.

The actual code fix will take a bit longer, because it requires some recording and editing, but I did make a note of the errata in https://github.com/mrosata/packt-mastering-fp/wiki/Errata
